server:
  type: BPP
  port: 5500
  sync_mode: true
log:
  level: DEBUG
  output_type: file
  out_file: log_file.log
path:
  search:
    schema:
      $ref: "https://raw.githubusercontent.com/abhinavv245/Json-store/main/schemas/Retail/search.json"
    callbacks:
      $ref: "./callbacks/on_search.yaml"
  # select:
  #   schema:
  #     $ref: "https://raw.githubusercontent.com/abhinavv245/Json-store/main/schemas/Retail/select.json"
  #   callbacks:
  #     $ref: "./callbacks/on_search.yaml"
  
      