server:
  type: BPP
  port: 5500
  sync_mode: false
log:
  level: DEBUG
  output_type: file
  out_file: log_file.log
path:
  search:
    schema:
      $ref: "https://raw.githubusercontent.com/abhinavv245/Json-store/main/schemas/Retail/search.json"
    callbacks:
      default:
        callback: on_search
        uri:
          operation:
            type: READ
            input:
              value: "req_body.context.bap_uri"
        delay: 300
        payload:
          $ref: "./template/on_search.yaml"