openapi: 3.0.0
info:
  title: ONDC Specification Stage 2
  description: ONDC Specification Stage 2
  version: 1.0.0

security:
  - SubscriberAuth: []
paths:
  /search:
    post:
      tags:
        - Provider Platform
        - Gateway
      description: Consumer Platform declares the customer's intent to buy/avail products or services
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/Search"
            examples:
              Example_0:
                $ref: "./examples/search/example_0.yaml"
              Example_1:
                $ref: "./examples/search/example_1.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /select:
    post:
      tags:
        - Provider Platform
      description: Consumer Platform declares the customer's cart (or equivalent) created by selecting objects from the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Select"
            examples:
              Example_0:
                $ref: "./examples/select/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /init:
    post:
      tags:
        - Provider Platform
      description: Initialize an order by providing billing and/or shipping details
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Init"
            examples:
              Example_0:
                $ref: "./examples/init/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /confirm:
    post:
      tags:
        - Provider Platform
      description: Initialize an order by providing billing and/or shipping details
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Confirm"
            examples:
              Example_0:
                $ref: "./examples/confirm/example_0.yaml"
              Example_1:
                $ref: "./examples/confirm/example_1.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /status:
    post:
      tags:
        - Provider Platform
      description: Fetch the latest order object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Status"
            examples:
              Example_0:
                $ref: "./examples/status/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  # /track:
  #   post:
  #     tags:
  #       - Provider Platform
  #     description: Track an active order
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "./io/index.yaml#/Track"
  #     responses:
  #       default:
  #         $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"
  # /cancel:
  #   post:
  #     tags:
  #       - Provider Platform
  #     description: Cancel an order
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "./io/index.yaml#/Cancel"
  #     responses:
  #       default:
  #         $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /update:
    post:
      tags:
        - Provider Platform
      description: Remove object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Update"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /rating:
    post:
      tags:
        - Provider Platform
      description: Provide feedback on a service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/Rating"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /support:
    post:
      tags:
        - Provider Platform
      description: Contact support
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/Support"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_search:
    post:
      tags:
        - Consumer Platform
      description: Provider Platform sends its catalog in response to a search request. 
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnSearch"
            examples:
              Example_0:
                $ref: "./examples/on_search/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_select:
    post:
      tags:
        - Consumer Platform
      description: Send draft order object with quoted price for selected items
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/OnSelect"
            examples:
              Example_0:
                $ref: "./examples/on_select/example_0.yaml"
              Example_1:
                $ref: "./examples/on_select/example_1.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_init:
    post:
      tags:
        - Consumer Platform
      description: Send order object with payment details updated
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/OnInit"
            examples:
              Example_0:
                $ref: "./examples/on_init/example_0.yaml"
              Example_1:
                $ref: "./examples/on_init/example_1.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_confirm:
    post:
      tags:
        - Consumer Platform
      description: Send active order object
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/OnConfirm"
            examples:
              Example_0:
                $ref: "./examples/on_confirm/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_track:
    post:
      tags:
        - Consumer Platform
      description: Send tracking details of an active order
      requestBody:
        content:
          application/json:
            schema:
              $ref : "./io/index.yaml#/OnTrack"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_cancel:
    post:
      tags:
        - Consumer Platform
      description: Send cancellation request_id with reasons list in case of cancellation request. Else send cancelled order object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnCancel"
            examples:
              Example_0:
                $ref: "./examples/on_cancel/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_update:
    post:
      tags:
        - Consumer Platform
      description: Returns updated service with updated runtime object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnUpdate"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_status:
    post:
      tags:
        - Consumer Platform
      description: Fetch the status of a Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnStatus"
            examples:
              Example_0:
                $ref: "./examples/on_status/example_0.yaml"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_rating:
    post:
      tags:
        - Consumer Platform
      description: Provide feedback on a service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnRating"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

  /on_support:
    post:
      tags:
        - Consumer Platform
      description: Contact Support
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./io/index.yaml#/OnSupport"
      responses:
        default:
          $ref: "../../../beckn-core-protocol-specs/api/transaction/components/io/Response.yaml"

components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using Consumer Platform or Provider Platform subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
  schemas:
    $ref: "../../../beckn-core-protocol-specs/api/transaction/components/schema/index.yaml"
  x-enum:
    $ref: "./enum/index.yaml"
